### ISSUE TITLE
Could not use latest `14.2.0` version because of `intl` version mismatch

### ISSUE THREAD

**Issue by bambinoua** [joanpablo/reactive_forms#365]
When I change my `pubspec.yaml`:
```yaml
dependencies:
  ...
  intl: ^0.18.0
  reactive_forms: ^14.2.0
```
I get the error that `flutter_localization` supports only `0.17.0` so I need to rollback to `intl 0.17.0` but then I cannot use `reactive_forms: ^14.2.0`.
